name: "Branch Prefix Version Bump"
description: "Customer GitHub action designed to version bump your tools based of the branch versions that have been merged into the stable code branch"

runs:
  using: node16
  main: index.js

inputs:
  version:
    description: "Semver package/library version"
    required: true
  major-prefixes:
    description: "Major version branch prefixes"
    required: true
  minor-prefixes:
    description: "Minor version branch prefixes"
  patch-prefixes:
    description: "Patch version branch prefixes"
  base-ref:
    description: "The ref of the stable point in time"
    required: true
  current-ref:
    description: "The ref that contains the latest branches"
    required: true

outputs:
  bumped-version:
    description: "The bumped up package version"
